name: Native-Stitcher GitHub Actions
on: push

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y build-essential

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-gcc make

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install gcc make

      - name: Build
        run: git clone https://github.com/libjpeg-turbo/libjpeg-turbo.git && ./build.sh  build macos
